### ISSUE TITLE
Updating from couter-up

### ISSUE THREAD

**Issue by BhaveshSGupta** [bfintal/Counter-Up2#1]
Hello,

I was using Counter-up in my site, I just updated jQuery version in the site to 3.3.1. Can you please in a demo where a user who is using jQuery can use this. too. Something similar to https://github.com/bfintal/Counter-Up/blob/master/demo/demo.html

**Comment by bfintal** [comment]
Hi, unlike the old counter-up, this one doesn't require jQuery.

The usage is available in the readme: https://github.com/bfintal/Counter-Up2
