### ISSUE TITLE
Thousand / decimal separator

### ISSUE THREAD

**Issue by andresilva-cc** [bfintal/Counter-Up2#3]
How can I configure the thousand / decimal separator? I need to display this number 1.000.000 (one million) and here in Brazil we use dots "." instead of commas "," as a thousand separator, while the decimal separator is a comma.

**Comment by shepelevstas** [comment]
In Russia we also use dots as thousand separator and comma as float separator. Also there is a need sometimes to use space or dash or minus '-' as sousand separator.

**Comment by vincentvermeer** [comment]
Same here, i need points as thousand seperator and comma as decimal seperator
