### ISSUE TITLE
How to set start number?

### ISSUE THREAD

**Issue by jinyang1994** [bfintal/Counter-Up2#5]
I want to set a start number and end number.

Example: 
```html
<div id="number">10000</div>
```

```javascript
counterUp(document.getElementById('number'), {
    start: 2000, // start number
    duration: 1000,
    delay: 16,
});
```

**Comment by adamjohnson** [comment]
I too would love to see an API for the start number.

Could also be the minimum amount of digits to start counting from. Eg: If my number is 1,500, I could set `minDigits` to `4` so that it never starts with a number below 1,000.
